config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # API routes

  mount ActionCable.server => '/cable'
  devise_for :users
  namespace :api, defaults: { format: :json } do
    namespace :v1 do

      mount_devise_token_auth_for 'User', at: 'auth'

      concern :votable do
        member do
          post :toggle_upvote
          post :toggle_downvote
        end
      end

      resources :countries, only: [:index]
      resources :specialties, only: [:index]
      resources :specialty_requests, only: [:create]
      resources :fields, only: [:index]
      resources :notifications, only: [:index]

      resources :users, only: [:show] do
        resources :posts, only: [:index]

        collection do
          get :search
        end

        member do
          post :add_friend
          post :follow

          put :accept_friend_request

          delete :cancel_friend_request
          delete :unfriend
          delete :unfollow
        end
      end

      resources :posts, only: [:create, :show, :update, :destroy], concerns: :votable do
        resources :comments, only: [:index, :create]

        collection do
          get 'global_beehive'
          get 'local_beehive'
          get 'specialty_beehive'
          get 'my_beehive'
        end
      end

      resources :comments, only: [:update, :destroy], concerns: :votable

      resources :chat_rooms, only: [:index, :create, :show, :update, :destroy] do
        member do
          post :participants, to: 'chat_rooms#add_participant'

          delete :participants, to: 'chat_rooms#remove_participant'
          delete :leave
        end
      end

      resources :research_teams, only: [:index, :show, :create, :update, :destroy] do
        post :posts, to: 'posts#create_post_for_research_team'

        collection do
          get :search
        end

        member do
          get :posts
          get :members, to: 'research_teams#list_members'

          post :members, to: 'research_teams#add_member'
          post :join

          delete :members, to: 'research_teams#remove_member'
          delete :leave
        end
      end
    end
  end

  scope constraints: -> (request) { request.format != :json } do
    # this matches ALL paths to bootstrapper action
    root to: 'react#bootstrapper'
    get '*path', to: 'react#bootstrapper'
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  include PublicActivity::Model

  #-------------------------------- Plugins -----------------------------------
  self.per_page = 10
	acts_as_votable
  act_as_mentioner

  # Accessors

  attr_accessor :mentionees_ids

  #------------------------------ CallBacks --------------------------------

  after_create :process_comment_mentions

	#after_create_commit {
    #NotificationSingleBroadcastJob.perform_later(
      #"commented on your post ",
      #Rails.application.routes.url_helpers.post_path(self.post.id),
      #self.post.author,
      #self.user,
      #Time.now.to_s
    #)
  #}

  #------------------------------ Associations --------------------------------

  belongs_to :post
  belongs_to :user
  alias_attribute :author, :user

  #---------------------------------- Scopes ----------------------------------

  def self.default_scope
    where(deleted: false).order(created_at: :desc)
  end

  #------------------------------- Validations --------------------------------

  validates_presence_of :content, :user, :post

  validates :content, length: { minimum: 1 }, allow_blank: true

  private

  def process_comment_mentions
    if(mentionees_ids)
      NotificationMultipleBroadcastJob.perform_later(
        "Mentioned you in a comment",
        Rails.application.routes.url_helpers.post_path(self.post.id),
        mentionees_ids,
        self.user,
        Time.now.to_s
      )
     end

     mentionees_ids = nil
  end
end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < Api::BaseController
  before_action :authenticate_user!
  before_action :set_post, only: [:index, :create]
  after_action :create_notification, only: [:create]

  include MentionersModule
  include Votable
  include Authorable

  def index
    @comments = @post.comments.paginate(page: params[:page] || 1)
  end

  def create
    @comment = @post.comments.new(user: current_user, content: params[:comment][:content])
    if @comment.save
      handle_mentions(@comment, @comment.post.research_team) # in MentionersModule
    else
      render json: @comment.errors.full_messages, status: 422
    end
  end

  private

  def create_notification
    return if current_user == @comment.post.author

    Api::V1::NotificationJob.perform_later(@comment, {
      key: "comment.created",
      owner: current_user,
      recipient: @comment.post.author,
      parameters: {
        author_name: @comment.author.fullname,
        path: api_v1_post_path(@comment.post),
        resource: { type: @comment.post.class.name, id: @comment.post.id }
      }
    })
  end

  def comment_params
    params.require(:comment).permit(:content)
  end

  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  include MentionersModule

  before_action :authenticate_user!
  before_action :set_comment, only: [:toggle_downvote, :toggle_upvote]
  before_action :set_post, only: [:paginate, :create]

  def create
    @comment = Comment.new(
      content: params[:comment][:content],
      post: @post,
      user: current_user
    )

    handle_mentions(@comment, @comment.post.research_team) # in MentionersModule
    @comment.save
  end

  def paginate
    page_number = params[:page]
    @comments = @post.comments.paginate(page: page_number).order(created_at: :desc).reverse
  end

  def destroy
  end

  def toggle_upvote
    if current_user.liked? @comment
      @comment.unliked_by current_user
    else
      @comment.upvote_by current_user
      #TODO  : Add localization
      NotificationSingleBroadcastJob.perform_later("upvoted your comment ", post_path(@comment.post.id), @comment.user, current_user, Time.now.to_s)
    end

    render 'vote_toggled'
  end

  def toggle_downvote
    if current_user.disliked? @comment
      @comment.undisliked_by current_user
    else
      if current_user.liked? @comment
        @comment.unliked_by current_user
      end

      @comment.disliked_by current_user
      #TODO  : Add localization
      NotificationSingleBroadcastJob.perform_later("downvoted your comment", post_path(@comment.post.id), @comment.user, current_user, Time.now.to_s)
    end

    render 'vote_toggled'
  end
  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
  %w(up down).each do |dir|
    define_method "comment_thumbs_#{dir}_icon_class" do |comment|
      if current_user.send("voted_#{dir}_for?", comment)
        "fa fa-thumbs-#{dir}"
      else
        "fa fa-thumbs-o-#{dir}"
      end
    end
  end
end

app/views/comments/_comment.html.haml
.mt-comment
  .mt-comment-body
    .mt-comment-info
      .mt-comment-author.font-yellow-casablanca
        = "#{comment.user.fullname} (#{comment.user.username})"
      .mt-comment-date
        = comment.created_at
    .mt-comment-text
      = comment.content.html_safe

    %br

    = link_to toggle_upvote_comment_path(comment), remote: true, class: 'vote-btn btn btn btn-icon-only yellow-crusta' do
      %i{ class: comment_thumbs_up_icon_class(comment), id: "comment-#{comment.id}-thumbs-up-icon" }

    = link_to toggle_downvote_comment_path(comment), remote: true, class: 'vote-btn btn btn-icon-only yellow-crusta' do
      %i{ class: comment_thumbs_down_icon_class(comment), id: "comment-#{comment.id}-thumbs-down-icon"}

    %span.text-muted.bold{ id: "comment-#{comment.id}-vote-sum"}
      #{ comment.votes_for.up.size - comment.votes_for.down.size }

app/views/comments/create.html.haml
%h1 Comments#create
%p Find me in app/views/comments/create.html.haml

app/views/comments/create.js.haml
var new_comment = '#{j render 'comments/comment', comment: @comment}';
$(new_comment).hide().appendTo('#post-#{@comment.post.id}-comments').fadeIn();
$("#comment-content-post-#{@comment.post.id}").val("")

app/views/comments/destroy.html.haml
%h1 Comments#destroy
%p Find me in app/views/comments/destroy.html.haml

app/views/comments/paginate.js.haml
var comments = ''
- @comments.each do |c|
  comments += '#{j render 'comments/comment', comment: c}';

var post_comments_div = $('#post-#{@post.id}-comments');
$(comments).hide().prependTo(post_comments_div).fadeIn();

var pagination_link = $(post_comments_div).find('a');

- if @comments.count < 10
  pagination_link.remove()
- else
  pagination_link.attr("href", "#{j paginate_post_comments_path(@post, page: params[:page].to_i + 1)}");
  pagination_link.prependTo(post_comments_div);

app/views/comments/vote_toggled.js.haml
$('#comment-#{@comment.id}-vote-sum').text(#{@comment.votes_for.up.size - @comment.votes_for.down.size});
$('#comment-#{@comment.id}-thumbs-up-icon').removeClass().addClass('#{comment_thumbs_up_icon_class(@comment)}');
$('#comment-#{@comment.id}-thumbs-down-icon').removeClass().addClass('#{comment_thumbs_down_icon_class(@comment)}');
  