config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # API routes

  mount ActionCable.server => '/cable'
  devise_for :users
  namespace :api, defaults: { format: :json } do
    namespace :v1 do

      mount_devise_token_auth_for 'User', at: 'auth'

      concern :votable do
        member do
          post :toggle_upvote
          post :toggle_downvote
        end
      end

      resources :countries, only: [:index]
      resources :specialties, only: [:index]
      resources :specialty_requests, only: [:create]
      resources :fields, only: [:index]
      resources :notifications, only: [:index]

      resources :users, only: [:show] do
        resources :posts, only: [:index]

        collection do
          get :search
        end

        member do
          post :add_friend
          post :follow

          put :accept_friend_request

          delete :cancel_friend_request
          delete :unfriend
          delete :unfollow
        end
      end

      resources :posts, only: [:create, :show, :update, :destroy], concerns: :votable do
        resources :comments, only: [:index, :create]

        collection do
          get 'global_beehive'
          get 'local_beehive'
          get 'specialty_beehive'
          get 'my_beehive'
        end
      end

      resources :comments, only: [:update, :destroy], concerns: :votable

      resources :chat_rooms, only: [:index, :create, :show, :update, :destroy] do
        member do
          post :participants, to: 'chat_rooms#add_participant'

          delete :participants, to: 'chat_rooms#remove_participant'
          delete :leave
        end
      end

      resources :research_teams, only: [:index, :show, :create, :update, :destroy] do
        post :posts, to: 'posts#create_post_for_research_team'

        collection do
          get :search
        end

        member do
          get :posts
          get :members, to: 'research_teams#list_members'

          post :members, to: 'research_teams#add_member'
          post :join

          delete :members, to: 'research_teams#remove_member'
          delete :leave
        end
      end
    end
  end

  scope constraints: -> (request) { request.format != :json } do
    # this matches ALL paths to bootstrapper action
    root to: 'react#bootstrapper'
    get '*path', to: 'react#bootstrapper'
  end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  layout 'landing'

  def index
    redirect_to controller: :home if user_signed_in?
  end
end

app/helpers/landing_helper.rb
module LandingHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/landing/index.html.haml
.containerFlex
  .content
    .logoName
      =image_tag image_path('SB-Logo.png')
    / Form Module
    .module.form-module
      .form
        %h2 Create an account
        = form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f|
          = f.text_field :first_name, placeholder: 'First name', autofocus: true
          = f.text_field :last_name, placeholder: 'Last name'
          = f.email_field :email, placeholder: 'Email'
          = f.password_field :password, autocomplete: 'off', placeholder: 'Password'
          = f.password_field :password_confirmation, autocomplete: 'off', placeholder: 'Password Confirmation'
          = f.button 'Sign up'
      .form
        %h2 Login to your account
        = form_for(resource, as: resource_name, url: session_path(resource_name)) do |f|
          = f.email_field :email, placeholder: 'Email', autofocus: true
          = f.password_field :password, placeholder: 'Password', autocomplete: "off"
          - if devise_mapping.rememberable?
            .field
              = f.check_box :remember_me
              = f.label :remember_me
          = f.button 'Login'
          = link_to "Forgot your password?", new_password_path(resource_name)
      .cta
        %h1{:class => "SignToggle"} Register