config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # API routes

  mount ActionCable.server => '/cable'
  devise_for :users
  namespace :api, defaults: { format: :json } do
    namespace :v1 do

      mount_devise_token_auth_for 'User', at: 'auth'

      concern :votable do
        member do
          post :toggle_upvote
          post :toggle_downvote
        end
      end

      resources :countries, only: [:index]
      resources :specialties, only: [:index]
      resources :specialty_requests, only: [:create]
      resources :fields, only: [:index]
      resources :notifications, only: [:index]

      resources :users, only: [:show] do
        resources :posts, only: [:index]

        collection do
          get :search
        end

        member do
          post :add_friend
          post :follow

          put :accept_friend_request

          delete :cancel_friend_request
          delete :unfriend
          delete :unfollow
        end
      end

      resources :posts, only: [:create, :show, :update, :destroy], concerns: :votable do
        resources :comments, only: [:index, :create]

        collection do
          get 'global_beehive'
          get 'local_beehive'
          get 'specialty_beehive'
          get 'my_beehive'
        end
      end

      resources :comments, only: [:update, :destroy], concerns: :votable

      resources :chat_rooms, only: [:index, :create, :show, :update, :destroy] do
        member do
          post :participants, to: 'chat_rooms#add_participant'

          delete :participants, to: 'chat_rooms#remove_participant'
          delete :leave
        end
      end

      resources :research_teams, only: [:index, :show, :create, :update, :destroy] do
        post :posts, to: 'posts#create_post_for_research_team'

        collection do
          get :search
        end

        member do
          get :posts
          get :members, to: 'research_teams#list_members'

          post :members, to: 'research_teams#add_member'
          post :join

          delete :members, to: 'research_teams#remove_member'
          delete :leave
        end
      end
    end
  end

  scope constraints: -> (request) { request.format != :json } do
    # this matches ALL paths to bootstrapper action
    root to: 'react#bootstrapper'
    get '*path', to: 'react#bootstrapper'
  end
end

app/models/research_team.rb
class ResearchTeam < ApplicationRecord

  enum privacy: { visible: 0, secret: 1 } # visible must be 0 and secret must be 1. changing this order will destroy some postgresql queries.
  alias_attribute :deleted, :soft_deleted

  #------------------------------ Associations --------------------------------

  has_many :posts, dependent: :destroy

  has_many :research_team_memberships, dependent: :destroy

  has_many :members, through: :research_team_memberships, source: :user

  has_many :enrolled_members, -> { where research_team_memberships: { status: :enrolled } },
           through: :research_team_memberships, source: :user

  has_many :invited_members, -> { where research_team_memberships: { status: :invited } },
           through: :research_team_memberships, source: :user

  has_many :requesting_members, -> { where research_team_memberships: { status: :requested } },
           through: :research_team_memberships, source: :user

  has_many :admins, -> { where research_team_memberships: { admin: true } },
           through: :research_team_memberships, source: :user

  belongs_to :creator, class_name: 'User'

  belongs_to :specialty

  #---------------------------------- Scopes ----------------------------------

  def self.default_scope
    where(deleted: false)
  end

  #------------------------------- Validations --------------------------------

  validates_presence_of :creator, :specialty, :description, :name

  validates :specialty, inclusion: { in: Specialty.all }
  validates :description, length: { minimum: 15 }, allow_blank: true
  validates :name, length: { minimum: 3 }, format: /\A[\-\w\s\?]+\Z/,
                    allow_blank: true

  #-------------------------------- Callbacks ---------------------------------

  after_create :add_creator_as_admin_member

  private

  def add_creator_as_admin_member
    self.admins << self.creator
  end
end

app/controllers/api/v1/research_teams_controller.rb
class Api::V1::ResearchTeamsController < Api::BaseController
  before_action :authenticate_user!
  before_action :set_research_team, except: [:create, :index, :search]
  before_action :check_adminstration, only: [:update, :destroy, :remove_member]
  before_action :check_membership, only: [:add_member, :leave]

  def index
    @research_teams = current_user.research_teams.paginate(page: params[:page] || 1)
  end

  def search
    @research_teams = ResearchTeam.search(
      name_cont: params[:q]
    ).result(distict: true).paginate(page: params[:page] || 1)

    render "index"
  end

  def show
  end

  def create
    @research_team = current_user.owned_research_teams.new(research_team_params)

    unless @research_team.save
      render json: { "errors": @research_team.errors.messages }
    end
  end

  def update
    unless @research_team.update(research_team_params)
      render json: { "errors": @research_team.errors.messages }
    end
  end

  def destroy
    @research_team.deleted = true

    unless @research_team.save
      render json: { "errors": @research_team.errors.messages }
    end
  end

  def posts
    @posts = @research_team.posts.paginate(page: params[:page] || 1)
  end

  def list_members
    if params.has_key? :awaiting_members
      @members = @research_team.requesting_members
    else
      @members = @research_team.enrolled_members
    end
    @members.paginate(page: params[:page])
  end

  def add_member
    @user = User.find(params[:user_id])

    if @research_team.enrolled_members.include?(@user) || !current_user.friends.include?(@user)
      head :not_modified
    else
      if @research_team.requesting_members.include?(@user)
        @research_team.requesting_members.delete(@user)
      end
      head :ok if @research_team.enrolled_members << @user
    end
  end

  def join
    unless @research_team.members.include? current_user
      @research_team.requesting_members << current_user
      head :ok
    else
      head :not_modified
    end
  end

  def leave
    if (@research_team.admins - [current_user]).empty?
      render json: { "error": "Admins can't be empty" }, status: :not_modified
    else
      head :ok if @research_team.enrolled_members.delete(current_user)
    end
  end

  def remove_member
    user = User.find_by(id: params[:user_id])
    head :not_modified if user.nil?
    if (@research_team.admins - [user]).empty?
      render json: { "error": "Admins can't be empty" }, status: :not_modified
    else
      head :ok if @research_team.enrolled_members.delete(user)
    end
  end

  private

  def research_team_params
    params.require(:research_team).permit(:specialty_id, :name, :description)
  end

  def set_research_team
    @research_team = ResearchTeam.where(id: params[:id], deleted: false).first
    head :not_found if @research_team.nil?
  end

  def check_adminstration
    head :unauthorized unless @research_team.admins.include? current_user
  end

  def check_membership
    head :unauthorized unless @research_team.enrolled_members.include? current_user
  end
end

app/controllers/research_teams_controller.rb
class ResearchTeamsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_research_team, except: [:new, :create, :index]
  before_action :check_admin, only: [:destroy, :edit, :accept_member, :show_requesting_members, :invite_friend, :accept_member, :cancel_invitation, :remove_member]
  before_action :check_not_soft_deleted, except: [:new, :create, :index]
  before_action :check_member, except: [:new, :create, :index, :request_membership]


  def new
    @no_title = true
    @rt = ResearchTeam.new
  end

  def index
    sql1 = "select research_team_id from research_team_memberships where research_team_memberships.user_id = #{current_user.id}"
    sql2 = "select Distinct research_teams.* from research_teams,research_team_memberships where research_teams.privacy = 0 AND research_teams.soft_deleted = false AND research_teams.id NOT IN (#{sql1})"
    @non_joined_nor_requested_nor_invited_teams = ActiveRecord::Base.connection.exec_query(sql2)

    sql3 = "select Distinct research_teams.* ,research_team_memberships.status from research_teams,research_team_memberships
      where research_teams.privacy = 0 AND research_teams.soft_deleted = false AND research_team_memberships.user_id = #{current_user.id} AND research_team_memberships.research_team_id=research_teams.id"
    @joined_or_requested_or_invited_teams = ActiveRecord::Base.connection.exec_query(sql3)
    @current_user = current_user

    respond_to do |format|
      format.js { render :js => "window.location.href = '#{research_teams_path}'" }
      format.html
    end


  end

  def create
    @rt = ResearchTeam.new(research_team_params)
    @rt.creator = current_user
    @rt.specialty = current_user.specialty

    if @rt.save
      invitees_ids = params[:invitees_ids]
      invite_multiple_friends_method(invitees_ids)
      redirect_to @rt
    else
      render :new
    end
  end

  def edit
  end

  def show
    @title = @rt.name
    if(@limited)
      @membership = ResearchTeamMembership.where(user_id: current_user.id, research_team_id: @rt.id).first
    end
    respond_to do |format|
      format.js { render :js => " window.location.href = '#{research_team_path(@rt.id)}' "}
      format.html 
    end
  end

  def destroy
   rt =  ResearchTeam.find(params[:id])
   rt.update_attribute(:soft_deleted, true)
   rt.posts.each do|post|
    post.update_attribute(:deleted, true)
   end
    redirect_to root_path
  end

  def available_friends
    @friends = current_user.friends - @rt.members
    render layout: false
  end

  def team_members
    @memberships = @rt.research_team_memberships
    @current_user  = current_user
    render layout: false
  end

  def invite_friend
    friend_id = params[:friend_id]
    friend = User.find(friend_id)
    @name = friend.fullname
    if invite_friend_helper(friend_id)

      if(params[:from_auto_complete] == "true")
        render js: "{$('#feedback_div').html('#{@name} Successfully Invited !');$('#friend_invite_autocomplete')[0].value = '';};"
      else
        render js: "{ $('#rt-add-friend-#{friend_id}').fadeOut().remove() ; $('#rt-members-count').text(#{@rt.enrolled_members.count});}"
      end

    elsif @rt.invited_members.include? friend and params[:from_auto_complete] == "true"

      render js: "{$('#feedback_div').html('#{@name} is already invited to this team !');$('#friend_invite_autocomplete')[0].value = '';};"

    elsif @rt.enrolled_members.include? friend and params[:from_auto_complete] == "true"

      render js: "{$('#feedback_div').html('#{@name} is already a member of this team !');$('#friend_invite_autocomplete')[0].value = '';};"

    elsif @rt.requesting_members.include? friend and params[:from_auto_complete] == "true"

      team_membership = ResearchTeamMembership.where(user_id: friend_id, research_team_id: @rt.id).first
      if !team_membership.enrolled?
          team_membership.enrolled!
      end
      render js: "{$('#feedback_div').html('#{@name} was accepted as a member in this team. !');$('#friend_invite_autocomplete')[0].value = '';};"

    else
      render js: "{;}"
    end
  end

  def accept_member
    if User.exists? params[:requesting_member_id]
        @memberId = params[:requesting_member_id]
        @research_team_id = @rt.id
        team_membership = ResearchTeamMembership.where(user_id: params[:requesting_member_id], research_team_id: @rt.id).first
        if !team_membership.enrolled?
          team_membership.enrolled!
        end
        render js: "{$('#rt-#{@rt.id}-view-member-#{@memberId}').fadeOut().remove();  $('#rt-members-count').text(#{@rt.enrolled_members.count});}"
   else 
    render js: "{;}"
   end
 end

  def cancel_join_request
    rtm = ResearchTeamMembership.where(research_team_id: @rt.id, user_id: current_user.id).first
    if rtm && rtm.requested?
      rtm.destroy
      @request_membership_research_team_path = request_membership_research_team_path(@rt.id)
      @user_id = current_user.id
      @research_team_id = @rt.id
    else
      render js: "{;}"
    end
  end

  def accept_invitation
    rtm = ResearchTeamMembership.where(research_team_id: @rt.id, user_id: current_user.id).first
    if rtm && rtm.invited?
       rtm.enrolled!
       @research_team_path = research_team_path(@rt.id)
       @user_id = current_user.id
       @research_team_id = @rt.id
    else
      render js: "{;}"
    end
  end

  def cancel_invitation
    rtm = ResearchTeamMembership.where(research_team_id: @rt.id, user_id: params[:invited_member_id]).first
    if rtm && rtm.invited?
       rtm.destroy
       @research_team_path = research_team_path(@rt.id)
       @user_id = params[:invited_member_id]
       @research_team_id = @rt.id
       render js: "{$('#rt-#{@rt.id}-member-#{@user_id}-button').fadeOut().remove();}"
    else
      render js: "{;}"
    end
  end

  def remove_member
    member_to_remove = User.find(params[:enrolled_member_id])

    if member_to_remove
      if  @rt.members.include? member_to_remove
        ResearchTeamMembership.where(user_id: member_to_remove.id, research_team_id: @rt.id).first.destroy
        render js: "{$('#rt-#{@rt.id}-view-member-#{member_to_remove.id}').fadeOut().remove();  $('#rt-members-count').text(#{@rt.enrolled_members.count});}"
      else
        render js: "{;}"
      end
    else 
      render js: "{;}"  
    end


  end


  def request_membership
    rtm = ResearchTeamMembership.where(research_team_id: @rt.id, user_id: current_user.id).first
    if rtm
      render js: "{;}"
    else
      rtm = ResearchTeamMembership.new
      rtm.user_id = current_user.id
      rtm.research_team_id = @rt.id
      rtm.requested!
      rtm.save # not necessary as rtm.requested! will automatically save
      @cancel_request_research_team_path = cancel_join_request_research_team_path(@rt.id)
      @user_id = current_user.id
      @research_team_id = @rt.id
      NotificationMultipleBroadcastJob.perform_later("Asked to join research team #{@rt.name} that you manage.",
      show_requesting_members_research_team_path(@rt.id), @rt.admins.pluck(:id), current_user, Time.now.to_s)
    end
  end  

  def show_requesting_members
    requester_ids = ResearchTeamMembership.where(status: :requested, research_team_id: @rt.id).pluck(:user_id)
    @requesters = User.where(id: requester_ids)
    @rt_id = @rt.id
  end

  private

  def set_research_team
    @rt = ResearchTeam.find(params[:id])
  end

  def check_admin
    unless @rt.admins.include? current_user
      flash[:notice] = "You are not allowed to perfrm this operation."
      redirect_to root_path
    end
  end


  def check_member
    if ( (@rt.members.exclude? current_user) && @rt.secret?)
      flash[:notice] = "Sorry, You are not allowed to perform this action."
      redirect_to request.referer
    elsif @rt.enrolled_members.include? current_user
      @limited = false
    else
      @limited = true
    end
  end

  def research_team_params
    params.require(:research_team).permit(:name, :description)
  end

  def check_not_soft_deleted
    if(@rt.soft_deleted)
      redirect_to root_path
    end
  end

  def invite_friend_helper(friend_id)
    if User.exists? friend_id
      friend = User.find(friend_id)
      if current_user.friends.include?(friend) && @rt.members.exclude?(friend)
        @rt.invited_members << friend
        NotificationSingleBroadcastJob.perform_later("invited you to join his research team : #{@rt.name}", research_team_path(@rt.id), friend, current_user, Time.now.to_s)      
      else
        return false
      end
    else 
      return false
    end

    return true
  end



  def invite_multiple_friends_method(invitees_ids)
    if(invitees_ids != nil)
        invitees_ids.uniq.each do |friend_id|
          invite_friend_helper(friend_id)
      end
    end
  end

end

app/helpers/research_teams_helper.rb
module ResearchTeamsHelper
end

app/views/research_teams/_invitees.html.haml
#invitees_portion.col-md-4
  / This part is using the bare html form of the rails-jquery-autocomplete.
  / I found this more usable than the helper version
  - invitees_counter = 0
  - (invitees_counter..invitees_counter+2).each do 
    = hidden_field_tag "invitees_ids[]",'', id: "result_id_#{invitees_counter}"
    <input type="text" id="user_#{invitees_counter}" value data-autocomplete="/users/autocomplete_user_username?scope=friends_only" data-id-element="#result_id_#{invitees_counter}" class="ui-autocomplete-input" autocomplete="off">
    -invitees_counter=invitees_counter+1
    %br
  :javascript
    var invitees_counter = #{invitees_counter}
  = submit_tag "More ?", :id => "invite_more_to_research_team_button", :class => "btn cPostBtn cBtnArea yellow-crusta", :type => 'button' 
  %br

app/views/research_teams/_sidebar.html.haml
%li.heading
  %h3.uppercase.font-yellow-gold Research Beehive 
  %h3.uppercase.font-yellow-gold  ( Invite Bees! ) 
%li.nav-item
  =link_to research_teams_path  do
    %i.fa.fa-university.font-yellow
    %span.title.font-yellow  Join Research Team ?

%li.nav-item
  = link_to new_research_team_path do
    %i.icon-plus.font-yellow
    %span.title.font-yellow New Research Beehive
%li.nav-item
  %a.nav-link.nav-toggle{href: "javascript:;"}
    %span.title.font-yellow-gold My Research Beehives
    %span.selected
    %span.arrow
  %ul.sub-menu{style: "display: block;"}
    - current_user.research_teams.where(:soft_deleted => false).each do |rt|
      %li.nav-item
        = link_to rt, class: 'nav-link' do
          %span.title.font-yellow= rt.name

app/views/research_teams/accept_invitation.js.erb
      var button = $('#rt_index_userID_<%="#{@user_id}"%>_rtID_<%="#{@research_team_id}"%>');
      button.attr('value', 'Enter Team !');
      button.parent().attr('action',"<%= @research_team_path %>");
      button.parent().attr('method',"get");
      button.parent().removeAttr("data-remote");

app/views/research_teams/available_friends.html.haml
.row
  -if @friends.empty?
    .mt-element-ribbon.bg-grey-steel
      .ribbon.ribbon-shadow.ribbon-color-warning{ :style => "margin-left: .5cm;" }
        = "-- No Friends To Invite !"
  -else
    - @friends.each do |f|
      .col-md-12{ id: "rt-add-friend-#{f.id}" }
        .mt-element-ribbon.bg-grey-steel
          .ribbon.ribbon-shadow.ribbon-color-warning.uppercase
            = link_to user_path(f), class: 'bold font-white' do
              = f.fullname
          .ribbon-content
            %div
              .row.margin-bottom-10
                = render 'users/user_info_list', user: f
              .row
                .col-md-3{style: 'float: right'}
                  = link_to invite_friend_research_team_path(@rt.id, friend_id: f.id), remote: true, method: :post, class: 'btn yellow-crusta' do
                    Invite Member

app/views/research_teams/cancel_join_request.js.erb
      var button = $('#rt_index_userID_<%="#{@user_id}"%>_rtID_<%="#{@research_team_id}"%>');
      button.attr('value', 'Request Membership !');
      button.parent().attr('action',"<%= @request_membership_research_team_path %>");

app/views/research_teams/edit.html.haml
= render 'form'

app/views/research_teams/index.html.erb
<h1>Visible Research Teams</h1>

<ul class="chatListContainer">
<br>

<%@non_joined_nor_requested_nor_invited_teams.each do |research_team| %>

<div style="float: left">
<br>
<li>
<span style="float: left" class = "btn blue">
	<%= "#{research_team['name']}" %> 
</span>
<span style="float: left">
	<%=  button_to "Request Membership !", request_membership_research_team_path(research_team["id"]),:id => "rt_index_userID_#{@current_user.id}_rtID_#{research_team['id']}", :method => :post, remote: true, :class => "btn yellow-crusta" %>
</span>
</li>
</div>
<% end %>



<%@joined_or_requested_or_invited_teams.each do |research_team| %>

<div style="float: left">
<br>
<li>
<span style="float: left" class = "btn blue">
	<%= "#{research_team['name']}" %> 
</span>
<span style="float: left">

	<%if(research_team['status'] == 0) #enrolled %> 
	<%=  button_to "Enter Team !", research_team_path(research_team["id"]),:id => "rt_index_userID_#{@current_user.id}_rtID_#{research_team['id']}" ,
	:method => :get, :class => "btn yellow-crusta" %>

	<%elsif(research_team['status'] == 1) #requested %>
	<%=  button_to "Cancel Request !", cancel_join_request_research_team_path(research_team["id"]), :id => "rt_index_userID_#{@current_user.id}_rtID_#{research_team['id']}"  ,:method => :post	, remote: true, :class => "btn yellow-crusta" %>

	<%elsif(research_team['status'] == 2) #invited %>
	<%=  button_to "Accept Invitation !", accept_invitation_research_team_path(research_team["id"]),:id => "rt_index_userID_#{@current_user.id}_rtID_#{research_team['id']}"  ,:method => :post, remote:true, :class => "btn yellow-crusta" %>
	<%end%>
</span>
</li>
</div>
<% end %>

  




<br>
</ul>

app/views/research_teams/new.html.haml
= render 'form'

app/views/research_teams/request_membership.js.erb
    var button = $('#rt_index_userID_<%="#{@user_id}"%>_rtID_<%="#{@research_team_id}"%>');
    button.attr('value', 'Cancel Request !');
    button.parent().attr('action',"<%= @cancel_request_research_team_path %>");
    button.parent().removeAttr("data-remote");

app/views/research_teams/show.html.haml
.research_team{:id => @rt.id}
.col-md-8
  .row
    -if ! @limited
      .col-md-12.no-padding
        = render template: 'posts/new'
      .row
        .col-md-12.no-padding#posts-container
          - @rt.posts.reverse.each do |post|
            = render 'posts/post_portlet', post: post
    -elsif @membership # THIS CODE IS NOT DRY. THIS IS SOMEWHAT REPLICATION OF THE CODE IN THE INDEX VIEW.
      -if @membership.invited?
        =button_to "Accept Invitation !", accept_invitation_research_team_path(@rt.id),:id => "rt_index_userID_#{current_user.id}_rtID_#{@rt.id}"  ,:method => :post, remote:true, :class => "btn yellow-crusta"
      -elsif @membership.requested?
        =button_to "Cancel Request !", cancel_join_request_research_team_path(@rt.id), :id => "rt_index_userID_#{current_user.id}_rtID_#{@rt.id}"  ,:method => :post , remote: true, :class => "btn yellow-crusta"
    -else # limited and no membership means you need to request to join
      =button_to "Request Membership !", request_membership_research_team_path(@rt.id),:id => "rt_index_userID_#{current_user.id}_rtID_#{@rt.id}", :method => :post, remote: true, :class => "btn yellow-crusta"


.col-md-4
  .portlet.light.bordered
    .portlet-body
      %h4 Description
      .well=@rt.description
      %h4
        Members
        %span.badge.badge-warning#rt-members-count
          = @rt.enrolled_members.count
      - if @rt.admins.include? current_user
        %a.view-mem-btn.btn.yellow-crusta{ "data-rt-id" => @rt.id, "data-toggle" => "modal", href: '#members' }
          View All Members
        %br
        %br
        = button_to "Delete Research Team", research_team_path(:id => @rt.id), :method => :delete , :class => "btn yellow-crusta delete-research-team-button" 
        %br
        %a.add-mem-btn.btn.yellow-crusta{ "data-rt-id" => @rt.id, "data-toggle" => "modal", href: '#friends' }
          Invite Members
        %br
        %br
          = form_tag( {action: "invite_friend", controller: "research_teams", format: :js} ,{id:"friends-invite-auto-complete-form", remote: true} )  do
            = hidden_field_tag :friend_id,'', id: 'single_invite_autocomplete'
            = hidden_field_tag :from_auto_complete,'true'
            = autocomplete_field_tag :friend_invite_autocomplete,'', autocomplete_user_username_users_path(scope:"friends_only"), id_element: '#single_invite_autocomplete', placeholder: "Or Invite From Here ?", class: 'field'
          %div#feedback_div


- if @rt.admins.include? current_user
  #friends.modal.modal-ajax.fade{"aria-hidden" => "true", :role => "basic", :style => "display: none;", :tabindex => "-1"}
    .modal-dialog
      .modal-content
        .modal-header
          %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"}
            %h4.modal-title Invite a friend to the team
        .modal-body Loading...
        .modal-footer
          %button.btn.dark.btn-outline{"data-dismiss" => "modal", :type => "button"} Close

- if @rt.admins.include? current_user
  #members.modal.modal-ajax.fade{"aria-hidden" => "true", :role => "basic", :style => "display: none;", :tabindex => "-1"}
    .modal-dialog
      .modal-content
        .modal-header
          %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"}
            %h4.modal-title All Members
        .modal-body Loading...
        .modal-footer
          %button.btn.dark.btn-outline{"data-dismiss" => "modal", :type => "button"} Close

app/views/research_teams/show_requesting_members.html.haml
.row
  - @requesters.each do |r|
    .col-md-12{ id: "rt-#{@rt.id}-view-member-#{r.id}" }
      .mt-element-ribbon.bg-grey-steel
        .ribbon.ribbon-shadow.ribbon-color-warning.uppercase
          = link_to user_path(r), class: 'bold font-white' do
            = r.fullname
        .ribbon-content
          %div
            .row.margin-bottom-10
              = render 'users/user_info_list', user: r
            .row
              .col-md-3{style: 'float: right'}
                = link_to accept_member_research_team_path(@rt.id, requesting_member_id: r.id), remote: true, method: :post, class: 'btn yellow-crusta', id:"rt-#{@rt_id}-member-#{r.id}-button" do
                  Accept Request
  .col-md-12                
    = link_to research_team_path(@rt.id), method: :get, class: 'btn yellow-crusta' do
      Go To Research Team

app/views/research_teams/team_members.html.haml
.row
  - @memberships.each do |m|
    .col-md-12{ id: "rt-#{m.research_team_id}-view-member-#{m.user.id}" }
      .mt-element-ribbon.bg-grey-steel
        .ribbon.ribbon-shadow.ribbon-color-warning.uppercase
          = link_to user_path(m.user), class: 'bold font-white' do
            = m.user.fullname
        .ribbon-content
          %div
            .row.margin-bottom-10
              = render 'users/user_info_list', user: m.user
            .row
              .col-md-3{style: 'float: right'}
                -if m.user_id != @current_user.id
                  -if m.requested?
                    = link_to accept_member_research_team_path(@rt.id, requesting_member_id: m.user.id), remote: true, method: :post, class: 'btn yellow-crusta', id:"rt-#{m.research_team_id}-member-#{m.user.id}-button" do
                      Accept Request
                  -elsif m.invited?
                    = link_to cancel_invitation_research_team_path(@rt.id, invited_member_id: m.user.id), remote: true, method: :post, class: 'btn yellow-crusta', id:"rt-#{m.research_team_id}-member-#{m.user.id}-button" do
                      Cancel Invitation
                  -elsif m.enrolled?
                    = link_to remove_member_research_team_path(@rt.id, enrolled_member_id: m.user.id), remote: true, method: :post, class: 'btn yellow-crusta', id:"rt-#{m.research_team_id}-member-#{m.user.id}-button" do
                      Remove Member