config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # API routes

  mount ActionCable.server => '/cable'
  devise_for :users
  namespace :api, defaults: { format: :json } do
    namespace :v1 do

      mount_devise_token_auth_for 'User', at: 'auth'

      concern :votable do
        member do
          post :toggle_upvote
          post :toggle_downvote
        end
      end

      resources :countries, only: [:index]
      resources :specialties, only: [:index]
      resources :specialty_requests, only: [:create]
      resources :fields, only: [:index]
      resources :notifications, only: [:index]

      resources :users, only: [:show] do
        resources :posts, only: [:index]

        collection do
          get :search
        end

        member do
          post :add_friend
          post :follow

          put :accept_friend_request

          delete :cancel_friend_request
          delete :unfriend
          delete :unfollow
        end
      end

      resources :posts, only: [:create, :show, :update, :destroy], concerns: :votable do
        resources :comments, only: [:index, :create]

        collection do
          get 'global_beehive'
          get 'local_beehive'
          get 'specialty_beehive'
          get 'my_beehive'
        end
      end

      resources :comments, only: [:update, :destroy], concerns: :votable

      resources :chat_rooms, only: [:index, :create, :show, :update, :destroy] do
        member do
          post :participants, to: 'chat_rooms#add_participant'

          delete :participants, to: 'chat_rooms#remove_participant'
          delete :leave
        end
      end

      resources :research_teams, only: [:index, :show, :create, :update, :destroy] do
        post :posts, to: 'posts#create_post_for_research_team'

        collection do
          get :search
        end

        member do
          get :posts
          get :members, to: 'research_teams#list_members'

          post :members, to: 'research_teams#add_member'
          post :join

          delete :members, to: 'research_teams#remove_member'
          delete :leave
        end
      end
    end
  end

  scope constraints: -> (request) { request.format != :json } do
    # this matches ALL paths to bootstrapper action
    root to: 'react#bootstrapper'
    get '*path', to: 'react#bootstrapper'
  end
end

app/models/post.rb
class Post < ApplicationRecord
  #-------------------------------- Plugins -----------------------------------

  self.inheritance_column = nil
  self.per_page = 10
  acts_as_votable
  act_as_mentioner

  attr_accessor :tags_string
  #attr_accessor :research_team_id
  attr_accessor :mentionees_ids

  #---------------------------------- Enums -----------------------------------

  enum type: [:knowledge, :question]

  #------------------------------ Associations --------------------------------

  has_and_belongs_to_many :tags

  has_many :comments, dependent: :destroy

  belongs_to :author, class_name: 'User'
  belongs_to :specialty

  belongs_to :research_team, optional: true

  #---------------------------------- Scopes ----------------------------------

  def self.default_scope
    where(deleted: false).order(created_at: :desc)
  end

  #-------------------------------- Callbacks ---------------------------------

  before_validation :set_specialty_like_author, if: -> { knowledge? && !author.sb_member? }
  before_save :add_tags, if: -> { tags_string.present? }
  after_create :process_post_mentions

  #------------------------------- Validations --------------------------------

  validates_presence_of :author, :specialty, :content, :title

  validates :specialty, inclusion: { in: Specialty.all }, if: :question?
  validates :content, length: { minimum: 15 }, allow_blank: true
  validates :title, length: { minimum: 3 }, format: /\A[\w\s\?]+\Z/,
                    allow_blank: true

  validate :check_research_team_membership, if: -> { research_team.present? }

  #--------------------------------- Methods ----------------------------------

  private

  def set_specialty_like_author
    self.specialty = author.specialty
  end

  def add_tags
    tags_objs = Tag.sanitize_and_create_or_find(tags_string)
    self.tags << tags_objs.reject { |t| self.tags.include? t }.uniq
  end

  def process_post_mentions
    if(mentionees_ids)
      NotificationMultipleBroadcastJob.perform_later("Tagged you in a Post",
      Rails.application.routes.url_helpers.post_path(self.id), mentionees_ids, self.author, Time.now.to_s)
     end
     mentionees_ids = nil
  end

  def check_research_team_membership
    errors.add(:research_team, "Can not post in this research team") unless
      self.research_team.members.include?(self.author)
  end

  def process_possible_images

        page = Nokogiri::HTML  self.content
        page.css('img').each do |img_node|
            image_style =  img_node[:style]
            if (image_style)
                width = image_style[/width:(.*?)px;/m, 1]
                height = image_style[/height:(.*?)px;/m, 1]
                img_node[:style] = "width:#{width}px;height:#{height}px;max-width:100%;max-height:100%;"
            else
                img_node[:style] = "max-width:100%;max-height:100%;"
            end

            ## Enforcing https to avoid mixed content
            image_src = img_node[:src]


            ## These commented lines will be very useful if we decide to host images on our own server
            ## They will relate Images with the posts they belong to for security reasons.
            ## If we use a third party storage, anyone with the url might see the image.

            #image_id = image_src.match /\/([^\/]+)(?=\/[^\/]+\/?\Z)/
            #pic = Ckeditor::Picture.find(image_id[1].to_i)
            #pic.update_attribute(:post_id, self.id)

            if(image_src)
               image_src.gsub! 'http://', 'https://'
               img_node[:src] = image_src
            end

          set = Nokogiri::XML::NodeSet.new(page)
          set.push(img_node)
          set.wrap("<a href = '#{img_node[:src]}'> </a>")

        end
        self.content = page
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < Api::BaseController
  include Authorable
  include Votable

  before_action :authenticate_user!
  before_action :paginate, only: [
    :index, :global_beehive, :local_beehive, :my_beehive, :specialty_beehive
  ]

  # TODO move this shit to users controller, or not?
  def index
    @user = User.find(params[:user_id])
    @posts = @posts.where(author: @user)
  end

  def global_beehive
    @posts = @posts.all
    render :index
  end

  def local_beehive
    @posts = @posts.joins(:author).where(
      users: { country: current_user.country }
    )
    render :index
  end

  def my_beehive
    @posts = @posts.where(
      author: current_user.friends << current_user
    )
    render :index
  end

  def specialty_beehive
    @posts = @posts.where(
      specialty: current_user.specialty
    )
    render :index
  end

  def show
    @post = Post.find(params[:id])
  end

  def create_post_for_research_team
    @post = instantiate_for_current_user
    @post.research_team_id = params[:research_team_id]

    unless @post.save
      render json: { "erros": @post.errors.full_messages }, status: :not_acceptable
      return
    end

    render :create
  end

  def create
    @post = instantiate_for_current_user
    unless @post.save
      render json: @post.errors.full_messages
    end
  end

  private

  def instantiate_for_current_user
    current_user.posts.new(post_params)
  end

  def paginate
    @posts = Post.where(research_team: nil).paginate(page: params[:page] || 1)
  end

  def post_params
    params.require(:post).permit(:content, :title, :type, :specialty_id,
                                 :tags_string, :research_team_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include MentionersModule
  before_action :authenticate_user!
  before_action :set_post, only: [:show, :toggle_upvote, :toggle_downvote]

  def create
    rt = nil
    if post_params[:research_team_id].present?
      rt = ResearchTeam.find_by_id(post_params[:research_team_id])
      redirect_to root_path, error: 'Not Allowed' if
        rt.nil? || !rt.members.include?(current_user)

      post_params.delete post_params[:research_team_id]
    end

    @post = current_user.posts.new(post_params)
    @post.research_team = rt
    handle_mentions(@post, rt) # in MentionersModule
    @post.save
  end

  def show
    if(@post == nil || @post.deleted)
      flash[:error] = "Sorry, The post you requested cannot be found"
      redirect_to root_path
    end
  end

  def toggle_upvote
    if current_user.liked? @post
      @post.unliked_by current_user
    else
      @post.upvote_by current_user
      #TODO  : Add localization
      NotificationSingleBroadcastJob.perform_later("upvoted your post", post_path(@post.id), @post.author, current_user, Time.now.to_s)

    end

    render 'vote_toggled'
  end

  def toggle_downvote
    if current_user.disliked? @post
      @post.undisliked_by current_user
    else
      if current_user.liked? @post
        @post.unliked_by current_user
      end
      @post.disliked_by current_user
      #TODO  : Add localization
      NotificationSingleBroadcastJob.perform_later("downvoted your post", post_path(@post.id), @post.author, current_user, Time.now.to_s)

    end

    render 'vote_toggled'
  end

  private

  def set_post
    @post = Post.find_by(id:params[:id])
  end

  def post_params
    params.require(:post).permit(:content, :title, :type, :specialty_id,
                                 :tags_string, :research_team_id)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def post_portlet_icon_class(post)
    if post.type == 'question'
      'icon-question'
    else
      'icon-paper-plane'
    end
  end

  %w(up down).each do |dir|
    define_method "post_thumbs_#{dir}_icon_class" do |post|
      if current_user.send("voted_#{dir}_for?", post)
        "fa fa-thumbs-#{dir}"
      else
        "fa fa-thumbs-o-#{dir}"
      end
    end
  end
end

app/views/posts/_post_portlet.html.haml
.portlet.light{ id: "post-#{post.id}-portlet" }
  .portlet-title
    .caption
      %i.font-yellow-casablanca{ class: post_portlet_icon_class(post) }
      = link_to user_path(post.author), class: 'caption-subject bold font-yellow-casablanca' do
        = "#{post.author.fullname.upcase}"
        = "(#{post.author.title})" if post.author.title.present?
      %span.caption-helper
        = post.author.sb_member? ? post.specialty.aggregate_with_field : post.author.specialty.aggregate_with_field
      - if post.research_team.present? && controller_name != "research_teams"
        = link_to post.research_team, class: "caption-helper bold" do
          = "@#{post.research_team.name}"

  .portlet-body
    %h4.bold
      = post.title
    %p
      = post.content.html_safe
    %span.post-tags
      - post.tags.each do |t|
        .badge.badge-warning
          = t.name

    %hr/

    = link_to toggle_upvote_post_path(post), remote: true, class: 'btn btn-circle btn-icon-only yellow-crusta' do
      %i{ class: post_thumbs_up_icon_class(post), id: "post-#{post.id}-thumbs-up-icon" }

    = link_to toggle_downvote_post_path(post), remote: true, class: 'btn btn-circle btn-icon-only yellow-crusta' do
      %i{ class: post_thumbs_down_icon_class(post), id: "post-#{post.id}-thumbs-down-icon"}

    %span.text-muted.bold{ id: "post-#{post.id}-vote-sum"}
      #{ post.votes_for.up.size - post.votes_for.down.size }

    %hr/

    .mt-comments{ id: "post-#{post.id}-comments" }
      - if post.comments.any?
        - if post.comments.count >= 1
          - if controller_name == "posts"
            - comments = post.comments.paginate(page: 1).order(created_at: :desc)
            - if comments.count > 10
              = link_to "See more comments", paginate_post_comments_path(post, page: 2), remote: true
            - comments.reverse.each do |c|
              = render "comments/comment", comment: c
          - else
            = link_to "See more comments", post_path(post)
            = render "comments/comment", comment: post.comments.last

    = form_for(Comment.new(post: post), url: post_comments_path(post), remote: true, html: { method: :post, role: 'form'}) do |f|
      = f.text_area :content, placeholder: 'Write a comment', id: "comment-content-post-#{post.id}", class: 'form-control margin-top-10 comment-content-area', rows: 1
      = f.submit "Comment", class: 'btn yellow-crusta margin-top-10'

app/views/posts/create.js.haml
- unless @post.errors.any?
  $('form#new_post').trigger('reset');
  $('#tags-input').removeTag()
  $('#newPostClose').trigger('click');
  if($('.portlet-body').length == 1) location.reload();
  var new_post_portlet = '#{j render 'posts/post_portlet', post: @post}';
  $(new_post_portlet).hide().prependTo('#posts-container').fadeIn();
  CKEDITOR.instances.new_post_ck_content_id.setData("")
- else
  - @post.errors.full_messages.each do |v|
    toastr.error("#{v}")

app/views/posts/new.html.haml
.newpost.light.bordered
  .newpost-title
    .caption
      %i.fa.fa-edit.font-yellow-crusta
      %span.caption-subject.font-yellow-crusta.bold.uppercase New Post
      %i.fa.fa-times.closebtn#newPostClose{ style: "display:none; " }

  .newpost-body.form
    = form_for(post = Post.new, remote: true, html: { method: :post, role: 'form'}) do |f|
      .TitleArea
        = f.text_field :title, class: 'titleinput form-control', placeholder: 'Title...'

      .newpost-body-rest{ style: "display:none; " }

        .TypeArea
          = f.select :type, Post.types.keys, {}, { class: 'form-control typeSelect' }

        .specialtyArea{ class: ("hidden" unless current_user.sb_member?), id: ("post_specialty_group" unless current_user.sb_member?) }
          = f.select :specialty_id, grouped_options_for_select(fields, current_user.specialty_id), {}, { class: 'form-control' }
        .contentArea
          = f.cktext_area :content, id:"new_post_ck_content_id", placeholder: 'Content...', class: 'contentArea form-control margin-top-10', rows: 8
        .tagsArea
          = f.text_field :tags_string, value: '', placeholder: 'Tags...', class: 'form-control margin-top-10', id: 'tags-input'
          = f.hidden_field :research_team_id, value: params[:id] if controller_name == 'research_teams'

        .cBtnArea
          = f.submit class:'btn cPostBtn'

app/views/posts/show.html.haml
= render 'post_portlet', post: @post

app/views/posts/vote_toggled.js.haml
$('#post-#{@post.id}-vote-sum').text(#{@post.votes_for.up.size - @post.votes_for.down.size});
$('#post-#{@post.id}-thumbs-up-icon').removeClass().addClass('#{post_thumbs_up_icon_class(@post)}');
$('#post-#{@post.id}-thumbs-down-icon').removeClass().addClass('#{post_thumbs_down_icon_class(@post)}');